---
title: ovvesley.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    excerpt_separator: "<!--more-->"
name: ovvesley
description:
  meta: ovvesley
  subtitle: Blog do Wesley Ferreira.
author:
  name: Wesley Ferreira
  email: ovvesley@gmail.com
  info: 
url: 
baseurl: "/"
lang: pt-br
show-subtitle: true
display-social-icons: true
social-icons-open-newtab: true
footer-text: feito com carinho ❤ no Rio de Janeiro. <br/> <i> O tema utilizado nesse blog é um fork customizado de um tema Jekyll desenvolvido por <a href="http://stijnvc.github.io/holo-alfa/">Stijn</a> <i>
logo-image: 
theme-color-attr: "#00f0ff"
ms-tile-color: "#00f0ff"
theme-color: 0, 240, 255
text-color: 0, 0, 0
background-color: 255, 255, 255
display-author-post-page: true
display-author-front-page: true
date_format: "%b %-d, %Y"
nav-breaking-point: 520px
paginate: 3
display-next-prev-post: false
disqus-shortname: 
twitter: https://twitter.com/ovvesley
youtube: 
instagram: 
tumblr: 
facebook: 
google-plus: 
reddit: 
soundcloud: 
medium: 
linkedin: https://www.linkedin.com/in/ovvesley/
github: https://github.com/ovvesley
behance: 
codepen: 
dribbble: 
trello: 
stack-overflow: 
bitcoin: 
paypal: 
var_on_the_web: na internet
var_read: Leia mais
var_newer: Postagens mais recentes
var_older: Postagens mais antigas
var_next_post: Próximo publicação
var_previous_post: Publicação anterior
var_less_than_a_minute_read: menos de um minutinho para a leitura
var_min_read: minutinhos para ler
var_post_by: Post by
var_guest_post_by: Guest post by
var_your_email: ovvesley@gmail.com
var_your_message: brasiliano
exclude:
- vendor
highlighter: rouge
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
theme: jekyll-theme-tactile
